### PR TITLE
Add file3.txt

### PR DESCRIPTION
**Pull request by francoismienie**

### CODE REVIEW

**Comment by francoismienie** [comment]
Please revie login

**Review by Nicoleenm — CHANGES_REQUESTED** [review]
Please add the google login feature as well.
The Facebook login seems fine.

**Comment by francoismienie** [comment]
please review, google login added

**Review by Nicoleenm — CHANGES_REQUESTED** [review]
Please add a Twitter login feature

**Review by Nicoleenm — APPROVED** [review]
All good please merge

**Pull request merged**
